---
title: "Linear_Congruent_Random_Number_Generator"
author: "Yu DAI"
date: "7/9/2019"
output: html_document
---
'''
1. Function rand2() will generate uniform random number according to given seed
2. Function gassrand() will generate standard normal random number according to given seed
'''
```{r }
rand2<-function(numran,idum=-1){  
  IM1=2147483563
  IM2=2147483399
  IMM1=IM1-1
  IA1=40014
  IA2=40692
  IQ1=53668
  IQ2=52774
  IR1=12211
  IR2=3791
  NTAB=32
  NDIV=1+IMM1/NTAB
  #make sure that you initializa the generator with a non-positive idum. 
  if(idum>0){idum=-idum}
  
  idum2=123456789
  iv=rep(0,NTAB)
  iy=0
  #real number
  AM=1./IM1
  EPS=1.2e-7
  RNMX=1.-EPS#number very close to 1
  random<-rep(0,numran)
  icount=1
  for(icount in 1:numran){
    if(idum<=0){
      idum<-max(-idum,1)
      idum2=idum
      j=NTAB+8
      while(j>0){
        k<-as.integer(idum/IQ1)
        idum<-IA1*(idum-k*IQ1)-k*IR1
        if(idum<0){
          idum<-idum+IM1
        }
        if(j<33){iv[j]<-idum}
        j<-j-1
      }
      iy<-iv[1]
    }
    k<-as.integer(idum/IQ1)
    idum<-IA1*(idum-k*IQ1)-k*IR1
    if(idum<0){idum<-idum+IM1}
    k<-as.integer(idum2/IQ2)
    idum2=IA2*(idum2-k*IQ2)-k*IR2
    if(idum2<0){idum2<-idum2+IM2}
    j<-1+as.integer(iy/NDIV)
    iy<-iv[j]-idum2
    iv[j]<-idum
    if(iy<1){iy<-iy+IMM1}
    ran2<-min(AM*iy,RNMX)
    random[icount]<-ran2
  }
  return(random)
}
hist(rand2(10000))
```

```{r }
gassMap<-function(idum){
  #input: idum between 0 and 1
  #output: x,approximation to inverse normal cdf
  a0=2.50662823884
  a1=-18.61500062529
  a2=41.39119773534
  a3=-25.44106049637
  b0=-8.47351093090
  b1=23.08336743743
  b2=-21.06224101826
  b3=3.13082909833
  C<-c(0.3374754822726147,0.9761690190917186,0.1607979714918209
       ,0.0276438810333863,0.0038405729373609,0.0003951896511919
       ,0.0000321767881768,0.0000002888167364,0.0000003960315187)
  
  y<-idum-0.5
  if(abs(y)<0.42){
    r<-y*y
    x<-y*(((a3*r+a2)*r+a1)*r+a0)/((((b3*r+b2)*r+b1)*r+b0)*r+1)
  }
  else{
    r<-idum
    if(y>0){r<-1-idum}
    r<-log(-log(r))
    x<-C[1]+r*(C[2]+r*(C[3]+r*(C[4]+r*(C[5]+r*(C[6]+r*(C[7]+r*(C[8]+r*C[9])))))))
    if(y<0){x<-(-x)}
  }
  return(x)
}
#this is a function that generate normal distributed random number 
gassrand<-function(numran,idum=-1){
  if(idum>0){idum=-idum}
  randnum=rand2(numran,idum)
  gassRand=rep(0,length(randnum))
  for(i in 1:length(randnum)){
    gassRand[i]<-gassMap(randnum[i])
  }
  return(gassRand)
}
hist(gassrand(10000))
```

